[package]
name = "huff-compilation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
huff-analysis.workspace = true
huff-ast.workspace = true
evm-glue.workspace = true
